on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - dev
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          flutter-version: '2.0.3'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-api
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iPhones
          mkdir Payload
          cd Payload
          in -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphones/app.ipa"
          tag: v1.0.${{github.run_number}}
          token: ${{secrets.TOKEN}}

